config/routes.rb
Rails.application.routes.draw do
  get '/', to: 'landing_page#welcome'
  get 'welcome', to: 'landing_page#welcome'
  get 'welcome/:user', to: 'landing_page#welcome'
  get 'users/:id', to: 'users#show'
  get 'gossips/:id', to: 'gossips#show'
  get 'team', to: 'static_pages#team'
  get 'contact', to: 'static_pages#contact'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :user
  has_many :markings
  has_many :tags, through: :markings
end

app/models/marking.rb
class Marking < ApplicationRecord
  belongs_to :tag
  belongs_to :gossip
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :sender, class_name: "User"
  belongs_to :recipient, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :markings
  has_many :gossips, through: :markings
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :city
  has_many :gossips
  has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
  has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
  def show
    @gossip = Gossip.find(params[:id])
  end
end

app/controllers/landing_page_controller.rb
class LandingPageController < ApplicationController
  def welcome
    @gossips = Gossip.all
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def team
  end

  def contact
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @user_gossips = @user.gossips
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/landing_page_helper.rb
module LandingPageHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/gossips/show.html.erb
<h1>Potin n°<%= @gossip.id %></h1>
<br/>
<p>
    <strong><%= @gossip.title %></strong><br/>
    <%= @gossip.content %><br/>
    <br/>
    Créé le <%= @gossip.created_at.to_time.strftime("%m/%d/%Y") %> par <a href="/users/<%= @gossip.user.id %>"> <%= @gossip.user.first_name %> <%= @gossip.user.last_name %></a>
</p>

app/views/landing_page/welcome.html.erb
<h1>Bienvenue à The Gossip Project !</h1><br/>

<% if params[:user] != nil %>
<p><strong>Ravi de vous revoir ici, <%= params[:user].capitalize %> !</strong></p>
<% end %>

<p>Retrouvez ici tous les potins de la communauté et partagez les votres avec les autres membres Gossip !</p>

<% @gossips.each do |gossip| %>
<div class="card" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title"><%= gossip.title %></h5>
    <h6 class="card-subtitle mb-2 text-muted">Créé le <%= gossip.created_at.to_time.strftime("%m/%d/%Y") %></h6>
    <p class="card-text"><%= gossip.content %></p>
    <a href="gossips/<%= gossip.id %>" class="card-link">Lire plus</a>
  </div>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>The Gossip Project</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

</head>

<body>

  <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #4C4AC5;">
    <a class="navbar-brand" href="<%=welcome_path%>">The Gossip Project</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-item nav-link" href="<%=team_path%>">Team</a>
        <a class="nav-item nav-link" href="<%=contact_path%>">Contact</a>
      </div>
    </div>
  </nav>

  <%= yield %>
</body>
</html>

app/views/static_pages/contact.html.erb
<h1>Pour nous joindre, c'est par ici !</h1><br/>
<p>Vous pourrez prochainement remplir un formulaire ci-dessous pour nous contacter directement.<br/>
En cas de pépin, on sera toujours là pour vous répondre ;)</p>

app/views/static_pages/team.html.erb
<h1>La Team Gossip</h1><br/>
<p>La Team Gossip est à votre écoute !</p>

app/views/users/show.html.erb
<h1>Profil de <%= @user.first_name %> <%= @user.last_name %></h1>
<br/>
<div class="card" style="width: 18rem;">
    <img class="card-img-top" src="http://www.aovc.org/wp-content/uploads/2015/10/photo-%C3%A0-venir-400x369.jpg" alt="Card image cap">
    <div class="card-body">
        <h5 class="card-title"><%= @user.first_name %> <%= @user.last_name %></h5>
        <p class="card-text"><%= @user.city.name %><br/><%= @user.age %> ans</p>
        <p class="card-text">"<%= @user.description %>"</p>
        <p class="card-text">Membre depuis le <%= @user.created_at.strftime("%m/%d/%Y") %></p>
    </div>
</div>
<br/>
<% @user_gossips.each do |gossip| %>
<p>
    Potin n°<%= gossip.id %> | <strong><a href="/gossips/<%= gossip.id %>"><%= gossip.title %></a></strong>
</p>
<% end %>